### ISSUE TITLE
How to remove legend?

### ISSUE THREAD

**Issue by Zepeng-Mu** [NightingaleHealth/ggforestplot#1]
Hi,

Thank you for this wonderful package. I have been looking for a package like this for a long time.

I have one question. How can I remove the legend if I do not want it?
For example, in `ggolot2` I would do `p+theme(legend.position = "none")`.
But I cannot do this in `forestplot`, I guess that is because the theme is internally overwritten by `theme_forest`.

So I am wondering if there is a way to work around it?

Thanks!

**Comment by mariakalimeri** [comment]
Hi Phoenix!

Great to hear you find the package useful! It is still meant for further improvements, we know we can and want to improve several things but we haven't found the time.

I am mainly replying now to acknowledge receiving your message, but it is a hectic week as I have a deadline for tomorrow afternoon. I will mark your message as unread to get back to it tomorrow. I hope you are not in a huge hurry.

But quickly, yes, most likely this is because the theme is overwritten internally. I will check first if, in its current state, there is a work around. If not I'll try to push a fix.

Thanks for reaching out and sorry I can't respond immediately to this.

Best
Maria
________________________________

**Comment by acichonska** [comment]
Hi @Zepeng-Mu,

Can you confirm that you are using `ggforestplot::forestplot()` function, not `ggforestplot::plot_all_NG_biomarkers()`? 
In case of `ggforestplot::forestplot()`, you can remove the legend as follows:
 `ggforestplot::forestplot(...) + theme(legend.position = "none")`.

Best,
Anna

**Comment by Zepeng-Mu** [comment]
> Hi @Zepeng-Mu,
> 
> Can you confirm that you are using `ggforestplot::forestplot()` function, not `ggforestplot::plot_all_NG_biomarkers()`?
> In case of `ggforestplot::forestplot()`, you can remove the legend as follows:
> `ggforestplot::forestplot(...) + theme(legend.position = "none")`.
> 
> Best,
> Anna

Hi,

I tried again and it is indeed working. Yesterday I was trying to modify other aesthetics such as the color of axis labels in `theme`, but it did not seem to work. But when I tried just now, it is actually working. I guess yesterday there was some problem with my input.

So I do not have any problems right now, and this issue could be closed.
Thank you so much once again!

**Comment by mariakalimeri** [comment]
Alright! Glad this was solve fast. Not usually the case. And thanks @acichonska !
