### ISSUE TITLE
Installation hanging

### ISSUE THREAD

**Issue by jasmine9764** [NightingaleHealth/ggforestplot#5]
Hi there, 
Thank you for developing such an amazing tool! I am a Mac R user and has installed devtool before.
I was stuck in the installation command for more than half an hour. After several attempts including restarting my R, it still does not work.
Is there any command/thing that I can try to accelerate this process?
<img width="847" alt="Screenshot 2021-04-23 at 22 48 40" src="https://user-images.githubusercontent.com/68228917/115889319-6a3eb700-a486-11eb-9fa1-a075c616cd04.png">

**Comment by mariakalimeri** [comment]
It shouldn't take that long. Maybe a few of minutes in case you have none of the dependencies. I am not sure why it takes so long but can you try to just use the command in the console? I.e. not as part of a markdown chunk.

**Comment by mariakalimeri** [comment]
Here is a docker solution to use `ggforestplot`(which also suggests that your issue is specific to your environment)

```
# Assuming you have docker installed, run the following. (Mind that your home directory, the first field after the -v flag, is mounted onto the container so that any figures you save in the `/temp/` directory in the container, will also appear in your $HOME.) If you don't have the image `rocker/tidyverse:4.0.1` locally, it will take sometime to download first before running it.
docker run -e PASSWORD=1111 -p 8787:8787 -v $HOME/:/temp/ rocker/tidyverse:4.0.1
```

When the above is "done", open your browser and go to `http://localhost:8787/`. Type username `rstudio` and password `1111`. You should be able to use RStudio the way you would locally. Save files in "/temp/". 

Now you should be able to install ggforestplot without an issue, at least I didn't have a problem and it took less than a minute. 

```
devtools::install_github("NightingaleHealth/ggforestplot")
```

I think we can close this issue now.
